# Generated by Django 2.2.10 on 2021-03-08 20:52

from django.db import migrations
import django_admin_filter.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_filter', '0004_auto_20210129_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterquery',
            name='querydict',
            field=django_admin_filter.models.JSONField(default=django_admin_filter.models.default_dict),
        ),
    ]
