# Generated by Django 2.2.10 on 2020-05-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('auto', models.AutoField(primary_key=True, serialize=False)),
                ('char', models.CharField(max_length=24)),
                ('text', models.TextField()),
                ('boolean', models.BooleanField()),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('smallinteger', models.SmallIntegerField()),
                ('integer', models.IntegerField()),
                ('positiveinteger', models.PositiveIntegerField()),
                ('positivesmallinteger', models.PositiveSmallIntegerField()),
                ('float', models.FloatField()),
                ('nullboolean', models.NullBooleanField()),
                ('slug', models.SlugField()),
                ('email', models.EmailField(max_length=254)),
                ('filepath', models.FilePathField()),
                ('url', models.URLField()),
                ('genericipaddress', models.GenericIPAddressField()),
                ('uuid', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
