# Generated by Django 2.2.10 on 2020-05-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField()),
                ('second', models.DecimalField(decimal_places=2, max_digits=5)),
                ('third', models.CharField(max_length=24)),
                ('forth', models.CharField(max_length=24)),
            ],
        ),
    ]
